language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=django==1.4.9
  - DJANGO=https://github.com/django/django/archive/stable/1.6.x.zip
install:
  - psql -c 'CREATE DATABASE orderable' -U postgres;
  - pip install $DJANGO --use-mirrors
  - pip install -r requirements.txt
  - pip install -e .
script: "make test"
notifications:
  email: false
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=django==1.4.9
